development:
  domain: localhost
  session_secret: 499529d9d6a48ff4bca1b4a1735404588f2cfdd968b62c8f
  deleted_user_email: 'deleted@example.com'
  google_analytics_id: 'UA-1234567-9'

test:
  domain: test.host
  session_secret: 499529d9d6a48ff4bca1b4a1735404588f2cfdd968b62c8f
  deleted_user_email: 'deleted@example.com'
  google_analytics_id: 'UA-1234567-9'
  
production:
  domain: example.com
  session_secret: 499529d9d6a48ff4bca1b4a1735404588f2cfdd968b62c8f
  deleted_user_email: 'deleted@example.com'
  google_analytics_id: 'UA-1234567-9'